name: lab3
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.0.1
  lints: ^3.0.0
  test: ^1.24.0
